### ISSUE TITLE
ECDSA implementation 

### ISSUE THREAD

**Issue by stevencedro** [armortal/webcrypto-go#2]
Implementation of ECDSA operations as per W3C specification at https://www.w3.org/TR/WebCryptoAPI/#ecdsa

**Comment by trancee** [comment]
@stevencedro did this get merged? I can't find the implementation anywhere :(

**Comment by stevencedro** [comment]
@trancee I haven't had a chance to implement this yet. I was waiting for someone to start requesting these features due to time constraints. I'll start working on it today and comment back here when it's done.

Thanks!

**Comment by stevencedro** [comment]
@trancee I added an issue #32 for the exportKey raw support. I'll get onto that after I finish #29. Do note though that it seems the WebCrypto spec states that exported ECDSA keys in raw format will only export `public` keys so if you wish to save your `private` key, according to the spec, it looks like only JWK and PKCS8 are supported. See https://www.w3.org/TR/WebCryptoAPI/#ecdsa-operations under `Export Key`.

Thanks!
